const players = [
  {
    id: 1,
    name: "Erling Haaland",
    age: 24,
    nationality: "Norwegian",
    club: "Manchester City",
    league: "Premier League",
    position: "Striker",
    overallRating: 92,
    isCaptain: false,
    skills: ["Finishing", "Pace", "Positioning", "Strength"],
    stats: {
      goals: 36,
      assists: 7,
      matches: 35,
      yellowCards: 3,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 180000000,
      contractUntil: "2028-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/418560-1695137434.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    nationalityFlag: "https://flagcdn.com/w320/no.png",
  },
  {
    id: 2,
    name: "Kylian Mbappé",
    age: 26,
    nationality: "French",
    club: "Real Madrid",
    league: "La Liga",
    position: "Forward",
    overallRating: 93,
    isCaptain: false,
    skills: ["Dribbling", "Pace", "Finishing", "Off the Ball"],
    stats: {
      goals: 34,
      assists: 12,
      matches: 37,
      yellowCards: 4,
      redCards: 1,
    },
    transferInfo: {
      marketValue: 200000000,
      contractUntil: "2029-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/342229-1695137415.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    nationalityFlag: "https://flagcdn.com/w320/fr.png",
  },
  {
    id: 3,
    name: "Lionel Messi",
    age: 38,
    nationality: "Argentinian",
    club: "Inter Miami",
    league: "MLS",
    position: "Attacking Midfielder",
    overallRating: 90,
    isCaptain: true,
    skills: ["Vision", "Dribbling", "Passing", "Free Kicks"],
    stats: {
      goals: 21,
      assists: 18,
      matches: 30,
      yellowCards: 2,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 25000000,
      contractUntil: "2026-12-31",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/28003-1695137319.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/f/f2/Inter_Miami_CF_logo.svg",
    nationalityFlag: "https://flagcdn.com/w320/ar.png",
  },
  {
    id: 4,
    name: "Jude Bellingham",
    age: 22,
    nationality: "English",
    club: "Real Madrid",
    league: "La Liga",
    position: "Midfielder",
    overallRating: 90,
    isCaptain: false,
    skills: ["Ball Control", "Passing", "Composure", "Tackling"],
    stats: {
      goals: 14,
      assists: 10,
      matches: 33,
      yellowCards: 6,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 150000000,
      contractUntil: "2029-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/581678-1695137448.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    nationalityFlag: "https://flagcdn.com/w320/gb.png",
  },
  {
    id: 5,
    name: "Kevin De Bruyne",
    age: 33,
    nationality: "Belgian",
    club: "Manchester City",
    league: "Premier League",
    position: "Midfielder",
    overallRating: 91,
    isCaptain: false,
    skills: ["Passing", "Crossing", "Vision", "Long Shots"],
    stats: {
      goals: 10,
      assists: 19,
      matches: 29,
      yellowCards: 3,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 75000000,
      contractUntil: "2027-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/88755-1695137354.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    nationalityFlag: "https://flagcdn.com/w320/be.png",
  },
  {
    id: 6,
    name: "Vinícius Júnior",
    age: 25,
    nationality: "Brazilian",
    club: "Real Madrid",
    league: "La Liga",
    position: "Left Winger",
    overallRating: 90,
    isCaptain: false,
    skills: ["Dribbling", "Acceleration", "Flair", "Creativity"],
    stats: {
      goals: 20,
      assists: 13,
      matches: 34,
      yellowCards: 5,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 160000000,
      contractUntil: "2028-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/371998-1695137438.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    nationalityFlag: "https://flagcdn.com/w320/br.png",
  },
  {
    id: 7,
    name: "Harry Kane",
    age: 32,
    nationality: "English",
    club: "Bayern Munich",
    league: "Bundesliga",
    position: "Striker",
    overallRating: 91,
    isCaptain: true,
    skills: ["Finishing", "Positioning", "Heading", "Leadership"],
    stats: {
      goals: 31,
      assists: 8,
      matches: 33,
      yellowCards: 2,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 110000000,
      contractUntil: "2028-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/132098-1695137384.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_M%C3%BCnchen_logo_(2017).svg",
    nationalityFlag: "https://flagcdn.com/w320/gb.png",
  },
  {
    id: 8,
    name: "Rafael Leão",
    age: 26,
    nationality: "Portuguese",
    club: "AC Milan",
    league: "Serie A",
    position: "Left Winger",
    overallRating: 88,
    isCaptain: false,
    skills: ["Dribbling", "Speed", "Creativity", "Finishing"],
    stats: {
      goals: 17,
      assists: 9,
      matches: 32,
      yellowCards: 4,
      redCards: 1,
    },
    transferInfo: {
      marketValue: 95000000,
      contractUntil: "2028-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/357662-1695137422.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg",
    nationalityFlag: "https://flagcdn.com/w320/pt.png",
  },
  {
    id: 9,
    name: "Florian Wirtz",
    age: 22,
    nationality: "German",
    club: "Bayer Leverkusen",
    league: "Bundesliga",
    position: "Attacking Midfielder",
    overallRating: 87,
    isCaptain: false,
    skills: ["Passing", "Dribbling", "Creativity", "Technique"],
    stats: {
      goals: 12,
      assists: 15,
      matches: 31,
      yellowCards: 3,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 100000000,
      contractUntil: "2027-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/564195-1695137446.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg",
    nationalityFlag: "https://flagcdn.com/w320/de.png",
  },
  {
    id: 10,
    name: "Christian Pulisic",
    age: 27,
    nationality: "American",
    club: "AC Milan",
    league: "Serie A",
    position: "Right Winger",
    overallRating: 84,
    isCaptain: false,
    skills: ["Dribbling", "Pace", "Finishing", "Agility"],
    stats: {
      goals: 9,
      assists: 8,
      matches: 29,
      yellowCards: 2,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 40000000,
      contractUntil: "2027-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/315779-1695137402.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg",
    nationalityFlag: "https://flagcdn.com/w320/us.png",
  },
  {
    id: 11,
    name: "Son Heung-min",
    age: 33,
    nationality: "South Korean",
    club: "Tottenham Hotspur",
    league: "Premier League",
    position: "Left Winger",
    overallRating: 88,
    isCaptain: true,
    skills: ["Finishing", "Pace", "Work Rate", "Ambidexterity"],
    stats: {
      goals: 18,
      assists: 10,
      matches: 34,
      yellowCards: 3,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 55000000,
      contractUntil: "2026-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/91845-1695137372.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg",
    nationalityFlag: "https://flagcdn.com/w320/kr.png",
  },
  {
    id: 12,
    name: "Lautaro Martínez",
    age: 28,
    nationality: "Argentinian",
    club: "Inter Milan",
    league: "Serie A",
    position: "Striker",
    overallRating: 89,
    isCaptain: true,
    skills: ["Finishing", "Positioning", "Agility", "Heading"],
    stats: {
      goals: 24,
      assists: 6,
      matches: 33,
      yellowCards: 4,
      redCards: 0,
    },
    transferInfo: {
      marketValue: 90000000,
      contractUntil: "2027-06-30",
    },
    photo:
      "https://img.a.transfermarkt.technology/portrait/header/406625-1695137427.jpg",
    teamLogo:
      "https://upload.wikimedia.org/wikipedia/en/0/05/Inter_Milan_logo_2021.svg",
    nationalityFlag: "https://flagcdn.com/w320/ar.png",
  },
];

export default players;
